server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/example/demo/mapper/xml/*.xml
  configuration:
    call-setters-on-nulls: true

# JWT配置
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加密使用的密钥
  secret: Mysecret
  # JWT 超期限时间(60*60*24)
  expire: 604800
  # JWT负载中拿到开头
  tokenHead: Bearer



